name: Test with Pi-hole

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      pihole:
        image: pihole/pihole:latest
        env:
          TZ: Europe/Berlin
          FTLCONF_webserver_api_password: test123

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        uses: ./
        with:
          pihole-app-password: "test123"
          pihole-url: "http://pihole/api"
          pihole-config-file: "./test/pihole-config-example.yaml"
